---
title: "TP4"
format: html
editor: visual
---

## 

```{r, message=FALSE}
library(here)
library(dplyr)
library(tidyr)
```

### 1

```{r}
here::i_am('r-101-grade-analysis.Rproj')
grades<-here('grades.csv')
grades<-read.csv(grades)

```

### 2

```{r}
t<-grades|>select(Exam)|>summarize(max=max(Exam, na.rm = T), med=median(Exam, na.rm = T), min=min(Exam,na.rm=T))


knitr::kable(t)


```

### 3

```{r}

absent<-grades|>select(Exam)|>
  summarise(Nombre_NA = sum(is.na(Exam)))
  


```

```         
Il y avait `r absent` personnes absentes à l'examen
```

### 4

```{r, message=F}

library(ggplot2)


exam_noNA<-grades|>select(Exam)|>na.omit()

ggplot(exam_noNA, aes(x=Exam))+
  geom_histogram(bin=30)+
  xlab("grade")

```

### 5

```{r}
table<-grades %>% group_by(Group) %>% summarise(count=n())

knitr::kable(table)
```

### 6

```{r}



ggplot(grades, aes(x=Group))+
  geom_bar(bin=30)+
  xlab("group")+
  theme(axis.text.x=element_text(angle = 45,hjust=1))
```

## 7

```{r}

ggplot(grades, aes(x=Exam))+
  geom_histogram(bin=30)+
  xlab("group")+
  facet_wrap(~Group)
  

```

```         
```

```{r}
ggplot(grades, aes(x = Group, y = Exam, fill=Group)) +
  geom_boxplot() +
  xlab("Groupe") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
 
```

```{r}

```

### 8

```{r}

missed_exam <- grades %>% filter(is.na(Exam))

missed_exam_count<- missed_exam %>%
  group_by(Group) %>%
  summarise(Num_Missed_Exam = n())

knitr::kable(missed_exam_count)
```

### 9

```{r}
ggplot(missed_exam_count, aes(x = Group, y = Num_Missed_Exam)) +
  geom_col(stat = "identity", fill = "blue") +
  xlab("Groupe") +
  ylab("Nombre d'Absents") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### 10

```{r}

grades_long <- pivot_longer(grades, 
                            cols = -c(Id, Group), #Colonnes d'identifiants (non pivotées)
                            names_to = "name",  # Nouvelle colonne pour stocker les noms des colonnes pivotées
                            values_to = "Values")# Nouvelle colonne pour stocker les valeurs pivotées

grades_long
```

### 11

```{r}

missed_exam_stud <- grades_long %>% filter(is.na(Values))

missed_exam_count_stud<- missed_exam_stud %>%
  group_by(Id) %>%
  summarise(Num_Missed_Exam_stud = n())

knitr::kable(missed_exam_count_stud)

```

The students that missed no exam do not appear.

### 12

```{}
```

```{r}
ggplot(missed_exam_count_stud, aes(x = Id, y = Num_Missed_Exam_stud)) +
  geom_bar(stat = "identity", fill = "orange") +
  xlab("student ID") +
  ylab("Number of missed exams") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### 13

```{r}

missed_exam_long <- grades_long %>% filter(is.na(Values))

missed_exam_count_long<- missed_exam %>%
  group_by(Group) %>%
  summarise(Num_Missed_Exam = n())

knitr::kable(missed_exam_count_long)
```
